# Generated by Django 4.1.7 on 2023-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
